use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Example' do
  pod 'CaamDauCompatible', '1.2.0'
  pod 'CaamDauEmpty', :path => '../'
end
